# -*- coding: utf-8 -*-
"""GenericFunctions

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11wzYpJLOxXh68xGS5IfVfOeh1yqla2WI
"""
import os, json
import numpy as np
from argparse import ArgumentParser
from tqdm import tqdm
from collections import defaultdict
import pandas as pd
from pprint import pprint
from datetime import datetime
import copy
import pickle
from ast import literal_eval
import re, string


def read_json_file(name):
    with open(name, 'r') as f:
        data = json.load(f)
        return data

#loading raw-predictions of the models for a dataset.
def get_raw_predictions_and_schema(path, dataset_name, model_name, prompt_type, version):
    data_path = os.path.join(path, 'Result')
    file_name = f'{model_name}-{prompt_type}-raw-predictions-{dataset_name}-v{version}.json'
    print(file_name)
    data = read_json_file(os.path.join(data_path, dataset_name, file_name))
    schema_path = os.path.join(path, 'Data')
    event_schema = read_json_file(os.path.join(schema_path, dataset_name, f'{dataset_name}_schema.json'))
    return data, event_schema

#function for normalizing the strings
def normalize_string(s):
      def white_space_fix(text):
          return ' '.join(text.split())
      def remove_punc(text):
          exclude = set(string.punctuation)
          return ''.join(ch for ch in text if ch not in exclude)
      def lower(text):
          return text.lower()
      return white_space_fix(remove_punc(lower(s.strip())))

#this will be used for normalizing the actual and predicted labels
def list_normalization(lst):
    normalized_lst = []
    for l in lst:
        normalized_lst.append(normalize_string(l)) #comment this when you do not want to normalize
        #normalized_lst.append(l) #comment this when you want to normalize
    normalized_lst = list(set(normalized_lst))
    return normalized_lst

#extracting the argument value from the string when json decode error arises
def find_argument_value(role, string_to_check):
    #print(role, string_to_check)
    value_list = ['null']  # set default value to null
    start_index = string_to_check.find(role)

    if start_index != -1:
        # Get the encapsulating character (' or ")
        if start_index > 0:
            finding_char = string_to_check[start_index - 1]
        else:
            return value_list  #no valid finding character

        start_index += len(role) + 2  #adjust start_index to start after role
        first_index = string_to_check.find(finding_char, start_index) + 1

        newline_index = string_to_check.find('\n', start_index)
        comma_index = string_to_check.find(',', start_index)
        if newline_index == -1: newline_index = float('inf')
        if comma_index == -1: comma_index = float('inf')
        newline_comma_index = min(newline_index, comma_index)

        # Handle null values
        if newline_comma_index <= first_index or first_index == 0:
            value_list = ['null']
            return value_list

        # Extract the value
        end_index = string_to_check.find(finding_char, first_index) #finding the last enclosing character
        value = string_to_check[first_index:end_index]
        value_list = value.split(";")  # Split the value by semicolon

    return value_list

#manually defining the function to extract values
def handle_json_decode_error(raw_pred, role):
    start_index = raw_pred.find('{') + 1
    end_index = raw_pred.find('}', start_index)

    string_of_interest = raw_pred[start_index:end_index] #most outpt is between {}. So this is our string of interest.
    value_list = find_argument_value(role, string_of_interest)
    return value_list

#processing the predictions for each role
def get_process_predictions(raw_pred, role, i):
    flag = 0
    try:
        data_dict = json.loads(raw_pred) #if we can simple load the value json.loads that is great.
        for key, value in data_dict.items():
            if value == None: #some of the prediction output is none. This raises json decode error. Just changing the value as null.
                #print(i, key, value)
                value = 'null'
            value = str(value) #converting the value to string other value.split() function gives error
            value_list = value.split(";")  #split the value by semicolon and store as a list

    #handling different types of exceptions. make the flag value=1 if any error arises
    except json.JSONDecodeError as e:
        flag = 1
        #print(f"JSON decoding error at index {i}: {e}")
    except KeyError as e:
        flag = 1
        #print(f"Missing key error at index {i}: {e}")
    except Exception as e:
        flag = 1
        #print(f"Unexpected error at index {i}: {e}")
    
        #if any error occured empty dict will be returned flag=1 and we will manually try to create the dictionary
    if flag == 1:
        #print(i, role, raw_pred) #to inspect the error
        value_list = handle_json_decode_error(raw_pred, role) #get values for all the roles of that sample when decoding error arises
        #print(value_list)
    
    return value_list, flag